"""add_host_hardware_fields

Revision ID: cafcb689650f
Revises: 001
Create Date: 2026-04-10 15:07:34.316906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cafcb689650f'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('cpu', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('memory', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('system_disk', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('data_disk', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'data_disk')
    op.drop_column('assets', 'system_disk')
    op.drop_column('assets', 'memory')
    op.drop_column('assets', 'cpu')
    # ### end Alembic commands ###