"""add_internal_external_address_fields

Revision ID: abc123def456
Revises: cafcb689650f
Create Date: 2026-04-10 17:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc123def456'
down_revision: Union[str, None] = 'cafcb689650f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('internal_address', sa.Text(), nullable=True))
    op.add_column('assets', sa.Column('external_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'external_address')
    op.drop_column('assets', 'internal_address')
    # ### end Alembic commands ###